name: tool
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - pip:
      - accelerate==0.16.0
      - anyio==3.6.2
      - click==8.1.3
      - colorama==0.4.6
      - diffusers==0.13.1
      - fastapi==0.92.0
      - filelock==3.9.0
      - ftfy==6.1.1
      - h11==0.14.0
      - huggingface-hub==0.12.1
      - importlib-metadata==6.0.0
      - packaging==23.0
      - psutil==5.9.4
      - pydantic==1.10.5
      - pyjwt==2.6.0
      - pyyaml==6.0
      - regex==2022.10.31
      - scipy==1.10.1
      - sniffio==1.3.0
      - starlette==0.25.0
      - tokenizers==0.13.2
      - torch==1.13.1
      - torchaudio==0.13.1
      - torchvision==0.14.1
      - tqdm==4.65.0
      - transformers==4.26.1
      - uvicorn==0.20.0
      - wcwidth==0.2.6
      - zipp==3.15.0